### ISSUE TITLE
Config entry override from env

### ISSUE THREAD

**Issue by aaydinyan** [rookie-ninja/rk-boot#55] opened 2022-01-17 00:11 UTC
**Describe the bug**
Config values in a ConfigEntry file cannot be overridden from env vars

**To Reproduce**
1. Create config entry in boot.yaml:
```config:
  - name: db-config
    locale: "*::*::*::*"
    path: config/db.yaml
```
2. Add name value pair in db.yaml config: `host: localhost`
3. Override from env `os.Setenv("host=anotherhost")`

**Expected behavior**
`rkentry.GlobalAppCtx.GetConfigEntry("db-config").GetViper().GetString("host")` should be equal "anotherhost"

**Comment by dongxuny** [comment] 2022-01-17 08:13
@aaydinyan Hi, I reproduced the bug and planned for bug fixing.

# Root cause
ConfigEntry init viper instance without enabling **viper.AutomaticEnv()**. I've tried bellow example with fixes.

- boot.yaml

```yaml
---
config:
  - name: db-config
    locale: "*::*::*::*"
    path: config/db.yaml
gin:
  - name: greeter
    port: 8080
    enabled: true
```

- config/db.yaml

```yaml
host: localhost
```

- main.go

```go
func main() {
        // As viper docs described, the env key should be upper case in order to override
        // https://github.com/spf13/viper
        // AutomaticEnv is a powerful helper especially when combined with SetEnvPrefix. When called, Viper will check for an 
        // environment variable any time a viper.Get request is made. It will apply the following rules. It will check for an 
        // environment variable with a name matching the key uppercased and prefixed with the EnvPrefix if set.
	os.Setenv("HOST", "anotherhost")

	// Create a new boot instance.
	boot := rkboot.NewBoot()

	fmt.Println(rkentry.GlobalAppCtx.GetConfigEntry("db-config").GetViper().GetString("host"))

	// Bootstrap
	boot.Bootstrap(context.Background())

	// Wait for shutdown sig
	boot.WaitForShutdownSig(context.Background())
}
```

- Output

```Shell script
anotherhost
```

# Fixes

```go
// enable automatic env
// issue: https://github.com/rookie-ninja/rk-boot/issues/55
entry.vp.AutomaticEnv()
entry.vp.SetEnvPrefix(entry.EnvPrefix)
```

- Enable AutomaticEnv() in viper instance
- Add envPrefix option in ConfigEntry, see example bellow:

- boot.yaml

```yaml
---
config:
  - name: db-config
    locale: "*::*::*::*"
    path: config/db.yaml
    envPrefix: rk     # default is empty string
gin:
  - name: greeter
    port: 8080
    enabled: true
```

- main.go

```go
func main() {
	os.Setenv("RK_HOST", "anotherhost")

	// Create a new boot instance.
	boot := rkboot.NewBoot()

	fmt.Println(rkentry.GlobalAppCtx.GetConfigEntry("db-config").GetViper().GetString("host"))

	// Bootstrap
	boot.Bootstrap(context.Background())

	// Wait for shutdown sig
	boot.WaitForShutdownSig(context.Background())
}
```

- Output

```Shell script
anotherhost
```

# Release procedure
1: bump up rk-entry to v1.0.5
2: bump up rk-boot to v1.4.2 with rk-entry@v1.0.5

# Estimated release time
By the end of today ( 2021-01.17 )

**Comment by dongxuny** [comment] 2022-01-17 09:35
@aaydinyan
Hi, bug was fixed with new release. Please [go get] bellow newest version of your dependencies based on web framework you use.

If non of web framework were used, please bump up rk-boot version to v1.4.2.

| Frameworks | Status | Tag | Installation | Dependency |
| --- | --- | --- | --- | --- |
| [gin-gonic/gin](https://github.com/gin-gonic/gin) | Stable | v1.2.15 | go get github.com/rookie-ninja/rk-boot/gin | [rk-gin](https://github.com/rookie-ninja/rk-gin) |
| [gRPC](https://grpc.io/docs/languages/go/) | Stable | v1.2.19 | go get github.com/rookie-ninja/rk-boot/grpc | [rk-grpc](https://github.com/rookie-ninja/rk-grpc) |
| [labstack/echo](https://github.com/labstack/echo) | Stable | v0.0.9 | go get github.com/rookie-ninja/rk-boot/echo | [rk-echo](https://github.com/rookie-ninja/rk-echo) |
| [gogf/gf](https://github.com/gogf/gf) | Stable | v0.0.8 | go get github.com/rookie-ninja/rk-boot/gf | [rk-gf](https://github.com/rookie-ninja/rk-gf) |
| [gofiber/fiber](https://github.com/gofiber/fiber) | Testing | v0.0.5 | go get github.com/rookie-ninja/rk-boot/fiber | [rk-fiber](https://github.com/rookie-ninja/rk-fiber) |
| [zeromicro/go-zero](https://github.com/zeromicro/go-zero) | Testing | v0.0.3 | go get github.com/rookie-ninja/rk-boot/zero | [rk-zero](https://github.com/rookie-ninja/rk-zero) |
| [gorilla/mux](https://github.com/gorilla/mux) | Testing | v0.0.3 | go get github.com/rookie-ninja/rk-boot/mux | [rk-mux](https://github.com/rookie-ninja/rk-mux) |

**Comment by dongxuny** [comment] 2022-01-25 10:21
The bug was fixed, closing issue.

**Closed by dongxuny** 2022-01-25 10:21 UTC
Labels: bug
